version: "3.1"

services:
  postgres:
    image: postgres:10
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      PGTZ: Europe/Moscow
    volumes:
      - ./docker/data/dump:/dump
      - ./docker/data/postgres:/var/lib/postgresql/data
    networks:
      - default


  nginx:
    image: nginx:1.15.0
    volumes:
      - ./../app:/var/www/app
      - ./docker/nginx/service.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    ports:
      - "8080:80"
    depends_on:
      - php-fpm


  php-fpm:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    working_dir: /var/www/app
    volumes:
      - ./../app:/var/www/app
    networks:
      - default
    depends_on:
      - postgres
